### ISSUE TITLE
Replace error messages with utility method

### ISSUE THREAD

**Issue by johnstamatakos** [PennTex/commuter#18]
Instead of 
`if err != nil {
	fmt.Printf(err.Error())
	panic(err)
}`

Use the utility method:
`utils.Check(err)`

**Comment by johnstamatakos** [comment]
@marioharper Need to discuss the handling of custom error messages vs. generic panics to get more consistency with our error handling.

**Comment by marioharper** [comment]
Can we just add a parameter to `utils.Check` to have a message to display if the check fails. If its an empty string throw the panic

**Comment by johnstamatakos** [comment]
Yeah that was one of my thoughts.  I can run with that.

Also, more descript name than `Check`
